[workspace]
resolver = "2"
members = [
    "crates/mw3-protocol",
    "crates/mw3-master",
    "crates/mw3-query-cli",
    "crates/mw3-dedi-launch",
    "crates/mw3-loader",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/"
